# Generated by Django 3.2.9 on 2021-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_invited', models.CharField(max_length=1000)),
                ('invited_by', models.CharField(max_length=1000)),
            ],
        ),
    ]
