# Generated by Django 3.2.9 on 2021-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='room_name',
            field=models.CharField(default='Test', max_length=1000),
        ),
    ]
