# Generated by Django 3.2.9 on 2021-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_invitation_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='room_name',
            field=models.CharField(max_length=1000),
        ),
    ]
