# Generated by Django 3.2.9 on 2021-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_invitation_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
